
# Online Retail customer segmentation
# Segmentation conducted based on Customer's purchase behavior, the features 
# analyzed are Recency, Frequency and Monetary Value, (RFM).

# Importing libraries
library(readxl)
library(dplyr)
library(ggplot2)
library(DT)
library(lubridate)
library(scales)
library(plotly)
library(ggthemes)

#Importing dataset (Nov 2016 to Dec 2017)
retail_data <- read.csv("Ecommerce.csv", stringsAsFactors = FALSE)
str(retail_data)
summary(retail_data)

#Preprocessing on the Dataset
# Date conversion into required format
retail_data$InvoiceDate <- as.Date(retail_data$InvoiceDate, "%d-%b-%y")

#Detecting and removing -ve values in column "Quantity and UnitPrice"
which(retail_data$Quantity<=0)
retail_data <- retail_data[-(which(retail_data$Quantity<=0)),]
which(retail_data$UnitPrice<=0)
retail_data <- retail_data[-(which(retail_data$UnitPrice<=0)),]

#Detecting and Removing missing values in column "CustomerID"
which(is.na(retail_data$CustomerID))
retail_data <- retail_data[-(which(is.na(retail_data$CustomerID))),]

#EDA on cleaned Dataset
# Top 11 countries by transaction (specifically 11 countries considered as transaction 
# after 11th country drops to less than 1000)
Transactions_per_Country <- retail_data %>%
  group_by(Country) %>%
  summarise('Number of Transactions' = n()) %>%
  arrange(desc(`Number of Transactions`)) %>%
  top_n(11)

names(Transactions_per_Country) <- c("Country", "Number of Transactions")
# Transaction for top 11 countries plot
Transaction_per_Country_plot <- ggplot(head(Transactions_per_Country,11), 
    aes(x=reorder(Country,-`Number of Transactions`), y=`Number of Transactions`)) +
  geom_bar(stat = 'identity', fill = 'steelblue') +
  scale_y_continuous(labels = comma) +
  geom_text(aes(label = `Number of Transactions`), vjust = -0.5) +
  ggtitle('Top 11 Countries by Number of Transactions') +
  xlab('Countries') +
  ylab('Number of Transactions')
print(Transaction_per_Country_plot)


# Recency(Time interval elapsed since last purchase of customer) EDA
# Recency is calculated as time of customer's last purchase minus last transaction date in days.
#Recency Summary
# 1. Most of the customers are active in the last 90 days(3 months).
# 2. some of the customers have over 140 days without making a single purchase.
# 3. 50% of the users are below 50 days of inactivity.
# 4. Small group of customers have not made a single transaction in over an year.
Customer_Recency <- retail_data %>% 
  group_by(CustomerID) %>%
  summarise(Last_Customer_Activity = max(InvoiceDate)) %>%
  mutate(Last_Invoice = max(Last_Customer_Activity))

Customer_Recency$Recency<- round(as.numeric(difftime(Customer_Recency$Last_Invoice, 
Customer_Recency$Last_Customer_Activity , units = c("days"))))

Customer_Recency <- Customer_Recency %>%
  select(CustomerID, Recency)
print(summary(Customer_Recency$Recency))
# Recency Histogram
ggplot(Customer_Recency, aes(Recency)) +
  geom_histogram() +
  ylab('Number of Customers')

DT::datatable((Customer_Recency),
              rownames = FALSE,
              options = list(
                pageLength = 10))

# Frequency (No. of times purchases made by customer) EDA
# Frequency is calculated based on the number of times a customer has made a 
# transaction in an year.
# Frequency Summary
# 1. Average of 90 transactions in an year.
# 2. 75% of users have less than 100 purchases a year.
# 3. Huge difference between the 3rd quartile and maximum number of purchases (7,812).
# Calculating the number of transaction per CustomerID
Customer_Frequency <- retail_data %>%
  group_by(CustomerID) %>%
  summarise(Frequency = n())
# Summary Statistics of Number of Purchases for each user
summary(Customer_Frequency$Frequency)
Customer_Frequency[Customer_Frequency$Frequency >=1500,]
# Frequency Histogram
ggplot(Customer_Frequency[Customer_Frequency$Frequency <=1500,], aes(Frequency)) +
  geom_histogram() +
  ylab('Number of Customers')

DT::datatable((Customer_Frequency),
              rownames = FALSE,
              options = list(
                pageLength = 10))

# Monetary Value (Revenue) EDA
# Calculating total sum of revenue(product of Unit Price and Quantity per transaction) 
# generated by the user over the course of a year.
# Monetory Summary
# 1. 75% of the customers contribute to revenue below 17K.
# 2. Average Revenue for customers is of 20K.
# 3. Huge difference between the 3rd quartile and maximum revenue (280206).
# Calculate Revenue per CustomerID
Customer_Monetary_Value <- retail_data %>%
  mutate(Revenue = Quantity * UnitPrice) %>%
  group_by(CustomerID) %>%
  summarise(Monetary_Value=sum(Revenue))
# Summary of Monetary Value 
summary(Customer_Monetary_Value$Monetary_Value)
Customer_Monetary_Value[Customer_Monetary_Value$Monetary_Value >=12000,]
Customer_Monetary_Value[Customer_Monetary_Value$Monetary_Value <=12000,]
# Monetary Value Histograms
ggplot(Customer_Monetary_Value[Customer_Monetary_Value$Monetary_Value<=12000,], aes(Monetary_Value)) +
  geom_histogram() +
  ylab('Number of Customers')

DT::datatable((Customer_Monetary_Value),
              rownames = FALSE,
              options = list(
                pageLength = 10))

# Recency, Frequency and Monetary Value merging
Customer_RFM <- merge(Customer_Recency, Customer_Frequency) # Merging Recency and Frequency
Customer_RFM <- merge(Customer_RFM, Customer_Monetary_Value) # Merging Monetary Value
DT::datatable((Customer_RFM),
              rownames = FALSE,
              options = list(
                pageLength = 10))

summary(Customer_RFM)
str(Customer_RFM)
# Detecting outliers in the data in terms of monetory value and frequency of purchase
# Outlier for Frequency and Monetory Value [Q3+1.5(Q3-Q1)] which is value above 
# 225 & 3693 as per our dataset. 

# Finding the outliers and removing them
# This appears to be a wholesale purchase (frequency is quite less and Monetary_Value is high)
# Hence can be removed from the list for consideration of loyalty program. 
nrow(Customer_RFM[Customer_RFM$Frequency<10 & Customer_RFM$Monetary_Value>3693,])
Customer_RFM <- Customer_RFM[-(which(Customer_RFM$Frequency<10 & Customer_RFM$Monetary_Value>3693)),]
nrow(Customer_RFM)

#This appears to be customers who have not made any purchases in the last 1 year and their 
# frequency of purchase was also quite less.Hence can be skipped for consideration of 
# loyalty program 
nrow(Customer_RFM[Customer_RFM$Recency>365 & Customer_RFM$Frequency<5,])
Customer_RFM <- Customer_RFM[-(which(Customer_RFM$Recency>365 & Customer_RFM$Frequency>5)),]
nrow(Customer_RFM)

# Clustering - KMeans 
# Creating Clusters based on the RFM
# Variables are measured in different units, where a unit increase or decrease for the Recency
# is completely different than a unit increase or decrease for the Monetary Value. 
# Therefore the data has been scaled in the kmeans algorithm. 
# Finding optimal clusters based on Elbow method
set.seed(100)
wss <- sapply(1:10, 
              function(k){kmeans(scale(Customer_RFM[,2:4]), 
                                 k, nstart = 50)$tot.withinss})
cluster <- data.frame(k = 1:10, WSS = wss)
cluster %>% 
  ggplot(aes(k, WSS)) + 
  geom_line() + 
  geom_point() + 
  geom_point(data = cluster %>% filter(k == 3), color = "red", size = 3) + 
  scale_x_continuous(breaks = seq(1, 10, by = 1)) + 
  labs(title = "Optimal Number of Clusters, Elbow Method", x = "Number of Clusters (K)") + 
  theme(panel.grid.minor = element_blank())

# KMeans Clustering with K = 3
set.seed(123)
Customer_Cluster <- kmeans(scale(Customer_RFM[,2:4]), 3, nstart = 1) 
# Performing kmeans with RFM variables and creating 3 clusters. 
Customer_RFM$Cluster <- as.factor(Customer_Cluster$cluster) 
# Attaching the results to CustomersID to identify each customer's cluster
KMeans_Cluster <- Customer_RFM %>%
  group_by(Cluster) %>%
  summarise('Number of Users' = n(),
            'Recency Mean' = round(mean(Recency)),
            'Frequency Mean' = scales::comma(round(mean(Frequency))),
            'Monetary Value Mean' = scales::dollar(round(mean(Monetary_Value))),
            'Cluster Revenue' = scales::dollar(sum(Monetary_Value))
  )
DT::datatable((KMeans_Cluster),
              rownames = FALSE) # Display cluster means
# Cluster plot
Cluster_size_visz <- ggplot(KMeans_Cluster, aes(Cluster, `Number of Users`)) +
  geom_text(aes(label = `Number of Users`), vjust = -0.3) +
  geom_bar(aes(fill=Cluster), stat='identity') +
  ggtitle('Number of Users per Cluster') + 
  xlab("Cluster Number") +
  theme_classic()
print(Cluster_size_visz)

# Extra Segmentation (for large cluster) - Hiererchical Clustering
set.seed(123)
library(rpart)
library(rpart.plot)
Cluster_1_Tree <- Customer_RFM %>%
  filter(Cluster == '1') %>%
  select(Frequency, Monetary_Value, Recency)

fit_tree <-rpart(Monetary_Value ~ ., 
                 data=Cluster_1_Tree,
                 method = 'anova', 
                 control= rpart.control(cp=0.0091452))
# optimal cp value
printcp(fit_tree)
plotcp(fit_tree)
#Large cluster detailed plot
rpart.plot(fit_tree, type=1,extra=1, box.palette=c("gray","lightblue"))

# Analysis
# KMeans clustering identified 3 customer clusters
# 1. Medium Value Customers - Cluster 1
# (i. 3217 customers, ii. Avg 40 days of inactivity, iii. Avg Frequency of purchase is 104.
# iv. Avg Revenue of $2030 an year , v. Cluster with highest revenue generated.
# 2. High Value Customers - Cluster 2
# i. 12 customers, ii. Avg 4 days of inactivity, iii. Avg Frequency of purchase is 2,779,
# iv. Avg Revenue of $122589 an year
# 3. Low Value Customers - Cluster 3
# i. 1,054 customers, ii. Avg 239 days of inactivity, iii. Avg Frequency of purchase is 28,
# iv. Avg Monetary Revenue of $536 a year.
# Further analysis using hierarchical clustering is conducted on cluster1(Medium value customers) 
# to understand deeper characteristics of the customers.
# This sub-segmentation of Cluster 1, divided the customers into 6 smaller different clusters.
# 1821 customers that purchased less than 70 times and has average monetary value of $751.
# 943 customers that purchase more than 70 times and has average monetary value of $2452
# (Significantly higher than the previous group)
# 282 customers that purchase less than 567 times and have purchased in the last 5 or more days
# and have Average Monetary Value of $4736.
# 120 customers that purchased less than 567 times and have not purchased within the last 
# less than 5 days and have Highest average monetary value of $7848.
# 44 customers that purchased more than or equal to 590 times and have 
# Highest average monetary value of $9092.
# 7 customers that purchased less than 590 times and have 
# Highest average monetary value of $25000 
# This last sub-segment of 7 customers represents the most valuable customers within Cluster 1. 
# From these insights, further strategic actions can be taken to increase the 
# average monetary value of sub-segments within this cluster of customers.











